spring:
    mvc:
      static-path-pattern: /static/**
    thymeleaf:
        mode: HTML
        encoding: UTF-8
        check-template-location: true
        prefix: classpath:/templates/
        suffix: .html
        cache: false
    web:
        resources:
            static-locations:
            - classpath:/static/
            cache: 
                period: 0
         
